l_english:
 SETTING_INPUT_CONTEXT_COMMON: "Стандартні"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Гарячі клавіші для стандартних елементів керування"
 
 SETTING_INPUT_ACTION_PAUSE: "Пауза / Відновити"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Підвищити швидкість"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Знизити швидкість"
 SETTING_INPUT_ACTION_SPEED_ONE: "Швидкість 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Швидкість 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Швидкість 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Швидкість 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Швидкість 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Пауза/Відтворення музики"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Наступна композиція"
 SETTING_INPUT_ACTION_CAMERA_UP: "Камера вгору"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Камера вліво"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Камера вниз"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Камера вправо"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Пошук локацій"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Політика"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Бюджет"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Споруди"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Ринок"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Збройні сили"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Дипломатія"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Технології"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Громада"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Населення"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Щоденник"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Блок держав"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Компанії"
 SETTING_INPUT_ACTION_MAP_LIST: "Літопис"
 SETTING_INPUT_ACTION_BACK: "Назад"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Планувальник"
 SETTING_INPUT_ACTION_TAB_1: "Вкладка 1"
 SETTING_INPUT_ACTION_TAB_2: "Вкладка 2"
 SETTING_INPUT_ACTION_TAB_3: "Вкладка 3"
 SETTING_INPUT_ACTION_TAB_4: "Вкладка 4"
 SETTING_INPUT_ACTION_TAB_5: "Вкладка 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Лінза виробництва"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Лінза політики"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Лінза дипломатії"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Лінза армії"
 SETTING_INPUT_ACTION_TRADE_LENS: "Лінза торгівлі"
 SETTING_INPUT_ACTION_CONFIRM: "Підтвердити"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Поточна ситуація"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Черга будівництва"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Зупинити/відновити чергу будівництва"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Відкрити відомості"
 SETTING_INPUT_ACTION_SCROLL_UP: "Вгору"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Вниз"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Показати закріплене в планувальнику"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Показати економіку в планувальнику"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Показати політику в планувальнику"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Показати дипломатію в планувальнику"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Показати збройні сили в планувальнику"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Показати все в планувальнику"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Закріпити/Відкріпити"
 SETTING_INPUT_ACTION_ZOOM_TO: "Наблизити"
 SETTING_INPUT_ACTION_MERGE: "Об’єднати"
 SETTING_INPUT_ACTION_COUNTRY_PANEL: "Детальні про країну"
